title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-f24/proj-courses-f24-01
owner: ucsb-cs156-f24
repo_name: proj-courses-f24-01
pull_requests: [{"author":{"id":"U_kgDOB8qFcQ","is_bot":false,"login":"cameronbyrne4","name":"Cameron Byrne"},"headRefName":"cameron-add-finals-info-service","number":31,"title":"Added backend methods and endpoints for finals information","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-01/pull/31"},{"author":{"id":"U_kgDOBcsK0A","is_bot":false,"login":"raychen179","name":""},"headRefName":"BetJobLog","number":29,"title":"Better Job Logs","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-01/pull/29"},{"author":{"id":"MDQ6VXNlcjczOTE2NDgw","is_bot":false,"login":"RealWeston34","name":"Scott Figueroa"},"headRefName":"COURSES-05-backend-error-when-adding-another-section-of-same-course-to-personal-schedule","number":28,"title":"Fix backend error message bug when adding a different section from an existing course in personal schedule.","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-01/pull/28"},{"author":{"id":"U_kgDOBcsK0A","is_bot":false,"login":"raychen179","name":""},"headRefName":"DescriptionOptional","number":27,"title":"Descriptional Optional","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-01/pull/27"},{"author":{"id":"MDQ6VXNlcjYxMzk0NTgx","is_bot":false,"login":"Neamal","name":"Junhyung Yoon"},"headRefName":"junhyung-cleanlog","number":25,"title":"deleted lines that caused clutter in my logs","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-01/pull/25"},{"author":{"id":"U_kgDOB8qFcQ","is_bot":false,"login":"cameronbyrne4","name":"Cameron Byrne"},"headRefName":"add-finals-info-service","number":24,"title":"Add finals info service and /api/finalsInfo endpoint","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-01/pull/24"}]
