
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-courses-f24-01
owner: ucsb-cs156-f24
repo_name: proj-courses-f24-01
pull_requests: [{"author":{"id":"U_kgDOB3DvtQ","is_bot":false,"login":"vincentc0202","name":""},"headRefName":"new-BetJobLog","number":37,"title":"New bet job log: Trying to fix the frontend mutations for AdminJobLogPage and JobsTable","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-01/pull/37"},{"author":{"id":"U_kgDOBcsK0A","is_bot":false,"login":"raychen179","name":""},"headRefName":"BetJobLog","number":29,"title":"Better Job Logs","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-01/pull/29"}]
