
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-courses-f24-01
owner: ucsb-cs156-f24
repo_name: proj-courses-f24-01
pull_requests: [{"author":{"id":"MDQ6VXNlcjYxNTcyODg3","is_bot":false,"login":"vzaveri23","name":"Viraj Zaveri"},"headRefName":"viraj-remove-stryker-exception","number":22,"title":"Added stryker test to check disableGroupBy is true for all columns","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-01/pull/22"},{"author":{"id":"U_kgDOB3DvtQ","is_bot":false,"login":"vincentc0202","name":""},"headRefName":"vincentc0202-duplicate-personalschedules","number":21,"title":"COURSES-1: Duplicate personalschedules edit bug fixed","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-01/pull/21"},{"author":{"id":"MDQ6VXNlcjczOTE2NDgw","is_bot":false,"login":"RealWeston34","name":"Scott Figueroa"},"headRefName":"COURSES-09-allow-admin-to-purge-job-log","number":20,"title":"Add Purge Job Log Button to Admin Jobs Page","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-01/pull/20"}]
